version: '3.8'

networks:
  todoDocker:
    driver: bridge

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - todoDocker

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydatabase
      DB_PORT: 5432
    networks:
      - todoDocker

  frontend:
    build: ./frontend/frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:5000
    networks:
      - todoDocker

volumes:
  pg_data: